# Generated by Django 2.0.4 on 2018-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=True, max_length=4),
        ),
    ]
